#: import get_color_from_hex kivy.utils.get_color_from_hex
MDScreen:
    name:"x"
    MDLabel:
        text: ""   
        pos_hint: {"center_x": 0.50, "center_y":0.85}
        halign:"center"

    MDLabel:
            markup:True
            text: "[color=#bae6bd][size=35]GECE SOFTWARE[/size][/color]"   #ş vb yazma
            font_name:"Constani.ttf"
            pos_hint: {"center_x": 0.50, "center_y":0.85}
            theme_text_color: "Secondary"
            halign:"center"
